export const VALIDATION_ERROR = {
    MISSING_CHAIN_ID: 'MISSING_CHAIN_ID',
    UNSUPPORTED_CHAIN_ID: 'UNSUPPORTED_CHAIN_ID',
    MISSING_TOKEN_BASE_ADDRESS: 'MISSING_TOKEN_BASE_ADDRESS',
    MISSING_TOKEN_QUOTE_ADDRESS: 'MISSING_TOKEN_QUOTE_ADDRESS',
    INVALID_TOKEN_ADDRESS: 'INVALID_TOKEN_ADDRESS',
    TOKEN_BASE_SAME_AS_TOKEN_QUOTE: 'TOKEN_BASE_SAME_AS_TOKEN_QUOTE',
    MISSING_INITIAL_VALUE: 'MISSING_INITIAL_VALUE',
    INVALID_INITIAL_VALUE: 'INVALID_INITIAL_VALUE',
    UNSUPPORTED_PAIR_TOKEN: 'UNSUPPORTED_PAIR_TOKEN',
    UNSUPPORTED_FEED_LIQUIDITY: 'UNSUPPORTED_FEED_LIQUIDITY',
}