export const VALIDATION_ERROR = {
    MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
    MISSING_CHAIN_ID: 'MISSING_CHAIN_ID',
    UNSUPPORTED_CHAIN_ID: 'UNSUPPORTED_CHAIN_ID',
    MISSING_CONTRACT_ADDRESS: 'MISSING_CONTRACT_ADDRESS',
    INVALID_CONTRACT_ADDRESS: 'INVALID_CONTRACT_ADDRESS',
    TOKEN_BASE_SAME_AS_TOKEN_QUOTE: 'TOKEN_BASE_SAME_AS_TOKEN_QUOTE',
    MISSING_AMOUNT: 'MISSING_AMOUNT',
    INVALID_AMOUNT: 'INVALID_AMOUNT',
    UNSUPPORTED_PAIR_TOKEN: 'UNSUPPORTED_PAIR_TOKEN',
    UNSUPPORTED_FEED_LIQUIDITY: 'UNSUPPORTED_FEED_LIQUIDITY',
}
export const CONTRACT_ERROR = {
    FUNCTION_NAME_NOT_FOUND: 'FUNCTION_NAME_NOT_FOUND',
}